server:
  port: 9091
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#    com Docker
#    defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: API-Gateway