FROM amazoncorretto:17-alpine
COPY eureka.jar eureka.jar
ENTRYPOINT [ "java", "-jar", "/eureka.jar" ]
#infnet/eureka
#aula-ms-network
#eureka-server
# cd Documents/Infnet/Projetos/Microsservicos/images/eureka
# docker build -t infnet/eureka .      
# docker run --name eureka-server --network aula-ms-network -p 8761:8761 infnet/eureka

