FROM amazoncorretto:17-alpine
COPY produto.jar produto.jar
ENTRYPOINT [ "java", "-jar", "/produto.jar" ]
#infnet/produto-service
#aula-ms-network
#eureka-server
# /Users/psyco/Documents/Infnet/Projetos/Microsservicos/images/produto
# docker build -t infnet/produto-service .
# docker run --network aula-ms-network infnet/produto-service                                                       

