FROM amazoncorretto:17-alpine
COPY api.jar api.jar
ENTRYPOINT [ "java", "-jar", "/api.jar" ]
#infnet/api
#aula-ms-network
#eureka-server
# /Users/psyco/Documents/Infnet/Projetos/Microsservicos/images/api-gateway
# docker build -t infnet/api-gateway .      
# docker run --name api-gateway --network aula-ms-network -p 9091:9091 infnet/api-gateway